### ISSUE TITLE
Invalid HTTP_HOST header: '_'. You may need to add '_' to ALLOWED_HOSTS.

### ISSUE THREAD

**Issue by bairhys** [mrmn2/PdfDing#24]
Hi @mrmn2 

I updated from 0.5.0 to 0.6.0 to test the new release with the same docker config and get this error:

```
Environment:


Request Method: GET
Request URL: http://server:5032/pdf/

Django Version: 5.1.3
Python Version: 3.12.7
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.openid_connect',
 'django_htmx',
 'huey.contrib.djhuey',
 'admin',
 'backup',
 'pdf',
 'users',
 'django_cleanup.apps.CleanupConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.LoginRequiredMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'allauth.account.middleware.AccountMiddleware',
 'django_htmx.middleware.HtmxMiddleware']



Traceback (most recent call last):
  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
    ^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: DisallowedHost at /pdf/
Exception Value: Invalid HTTP_HOST header: 'server:5032'. You may need to add 'server' to ALLOWED_HOSTS.
```

Then in the settings section:

```
Settings
....
ADMINS   []
ALLOWED_HOSTS  []
APPEND_SLASH   True
```

So nothing is getting passed through to `ALLOWED_HOSTS`?

I use Ansible to manage my PdfDing setup. When I set to `mrmn/pdfding:0.5.0`, PdfDing works as normal but when I change to `mrmn/pdfding:0.6.0` I get the above error:

```
- name: Create pdfding Docker Container
  docker_container:
    name: pdfding
    image: mrmn/pdfding:0.6.0
    pull: true
    ports:
      - "5032:5032"
    volumes:
      - "{{ pdfding_books_directory }}/pdfding:/home/nonroot/pdfding/media:rw"
      - "{{ pdfding_config_directory }}:/home/nonroot/pdfding/db:rw"
    restart_policy: unless-stopped
    env:
      TZ: "{{ nas_timezone }}"
      HOST_NAME: "server"
      SECRET_KEY: "{{ pdfding_secret }}"
      CSRF_COOKIE_SECURE: "FALSE"
      SESSION_COOKIE_SECURE: "FALSE"
      HOST_PORT: "5032"
```
