### ISSUE TITLE
Unable to use NFS volume

### ISSUE THREAD

**Issue by NotGreatWithCode** [mrmn2/PdfDing#88]
Pretty new to docker and homelabs in general, apologies for noob behavior.

I set up an NFS volume via Portainer before running compose.
NFS share is v4, squash is set to map all users as admin on my NAS (set it up this way to troubleshoot).
Using docker compose up returns: 
`Error response from daemon: failed to chmod on /var/lib/docker/volumes/pdf/_data: chmod /var/lib/docker/volumes/pdf/_data: operation not permitted`

```
services:
  pdfding:
    container_name: pdfding
    image: mrmn/pdfding:latest
    volumes:
      - sqlite_data:/home/nonroot/pdfding/db
      - pdf:/home/nonroot/pdfding/media
      # If you use selinux it might be necessary to add the :Z after the volume
      # - sqlite_data:/home/nonroot/pdfding/db:Z
      # - media:/home/nonroot/pdfding/media:Z
    environment:
      - DEFAULT_THEME=${DEFAULT_THEME:-dark}
      - DEFAULT_THEME_COLOR=${DEFAULT_THEME_COLOR:-blue}
      # use a long random secret
      - SECRET_KEY=${SECRET_KEY:-[secret]}
      # the domain where you want to access PdfDing, e.g. pdfding.com
      - HOST_NAME=${HOST_NAME:-192.168.0.78}
      # In production set the following values to True
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-'TRUE'}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-'TRUE'}
    ports:
      - "8020:8000"

volumes:
  sqlite_data:
  pdf:
    external: true
```

I'm not entirely sure but I think it has to do with the "nonroot" portion of the directory. Whenever I change out that portion for another name it just runs.
