### ISSUE TITLE
Internal Server Error upon uploading file

### ISSUE THREAD

**Issue by Cantello** [mrmn2/PdfDing#99]
I have installed pdfding via docker compose on an oracle VPS/oracle linux with sqlite database. The service is reverse proxied by [pangolin](https://github.com/fosrl/pangolin) on a subdomain, SSL by letsencrypt certificates.

**Whenever I try to upload a file larger than approx. 100MB, after a while an error message appears: `Internal Server Error`.**

The logs show the following: https://pastebin.com/fghHt0Lp

The compose.yaml is as follows:
```
  pdfding:
    container_name: pdfding
    image: mrmn/pdfding:latest
    volumes:
      - /opt/pdfding/data:/home/nonroot/pdfding/db
      - /opt/pdfding/media:/home/nonroot/pdfding/media
    environment:
      - HOST_NAME=pdfs.domain.org
    ports:
      - 8008:8000
    networks:
      - backend
 ```

Any idea what could cause this?
